### ISSUE TITLE
How to connect to Ostro on edison 

### ISSUE THREAD

**Issue by PaulB2Code** [ostroproject/meta-ostro#266]
Hi Ostro, 

I tried to install Ostro on my Edison .It seems working (the flashing) but I can not logging after that..

Is there a way to do it if auto-logging do not work.

Thank you for the help

![image](https://cloud.githubusercontent.com/assets/4618740/22347827/afb44e86-e409-11e6-8df7-64b41f1c5120.png)

**Comment by gvancuts** [comment]
Hi @PaulB2Code , can you tell us which image you have used? You should be automatically logged in as `root` on the serial line.

I'm assuming you have seen these instructions: [Installing Ostro on the Intel Edison board](https://ostroproject.org/documentation/howtos/booting-and-installation.html#intel-edison)?

Note that logging in via SSH requires extra steps, these are described on the [Adding Authorized Keys for Remote ssh Access](https://ostroproject.org/documentation/howtos/authorized-keys.html) page.

**Comment by PaulB2Code** [comment]
Hi @gvancuts , 

I used this image : https://download.ostroproject.org/releases/ostro-os/milestone/2016-05-02_00-09-47-build-440/images/edison/ostro-image-swupd-edison.toflash.tar.bz2

Then I extract it and use flasball.bat (I am on windows 10). But no auto logging. 

I will try on linux and see. 

Thank you

**Comment by gvancuts** [comment]
Did you have a login prompt to your Edison board before flashing Ostro on it?

There are two USB cables that you use with the Edison (and a switch to be set to the correct position). Can you confirm you have set those correctly? https://software.intel.com/en-us/node/628221

**Comment by PaulB2Code** [comment]
Yes, I was using poky Before. But I always have to connect through ssh after and I never get a login prompt command after a flash. 
I used the intel tool to connect to wifi and before ssh connection.

I will try with linux but I have to find a computer. 

I will keep you aware.

**Comment by gvancuts** [comment]
Hi @PaulB2Code , I'm not sure using Linux to flash the board will make any difference. You cannot simply use SSH with Ostro for security reasons, you'd have to provision your device image upfront before doing that, either by building your own image including your public key or by adding your public key to a running system (a serial connection is your only option in this case).

Note that the serial port is a different USB cable/connector than the one used for flashing the board (and you also need to toggle the little switch to the right position), please refer to this page for more details on how to set this up correctly: https://software.intel.com/en-us/node/628222#uartserial

Hope this helps!

**Comment by PaulB2Code** [comment]
Hi @gvancuts , 

In fact I try with linux and no difference..

In the flash.log, I have this error : 
"
state(2) = dfuIDLE, status(0) = No error condition is present
Done!
dfu-util: can't detach
Resetting USB to switch back to runtime mode
dfu-util: error resetting after download: LIBUSB_ERROR_NO_DEVICE
"

So without building my own ostro image and add an ssh, there is no other way ?

May I could be interesting for user prostective to have a conf file where we can place ssh information without a complete building.

**Comment by PaulB2Code** [comment]
Hi @gvancuts . 

I have build my own images with ssh but I stay stuck to find IP Adress of the device to test the connection.  I tried 192.168.2.2 but I always have port 22 : connection refused. 

I try with 
sudo screen /dev/ttyUSB0 115200

and it works perfectly. Is it ok ? or is there another or better way?

And when i tap : 
uname -r 
I do not see ostro.

Looking forward

Thank you

**Comment by gvancuts** [comment]
Hi @PaulB2Code , it looks like you've got it mostly working now!

From the 'screen' session, use:
* `ifconfig` to determine the IP address of your device and use that with SSH
* `cat /etc/os-release` to see exactly what version of Ostro OS you're running

If you don't want to build your own image, the only mechanism is to add your key via the `screen` session (which you now have working). So:
1. Flash a pre-built image downloaded from the website
2. Boot up the Edison board
3. Connect via `screen`
4. Edit the authorized_keys file: `vi ~/.ssh/authorized_keys`
5. Copy-paste your public key file in there
6. Reboot the device and you can now log in via SSH (your IP address may have changed after the reboot, so double-check it if you get a `port 22 : connection refused` error again)

Thanks

**Comment by PaulB2Code** [comment]
Hi @gvancuts , 

Now it works perfectly. 

For our project we want to build a custom system for our need. 
And for our test we want to enable package installation before finalize our package choice. 

We have enable following this tuto :https://ostroproject.org/documentation/howtos/building-images.html

But we do no have either opkg or ipkg.

We have opkg.py, opkg-build, etc..  But no opkg. 

How could we valid our installation process to enable package installation.

Thank you again.

**Comment by gvancuts** [comment]
Hi @PaulB2Code , great, glad to hear it works fine now!

Ostro does not use packages but uses bundles as part of its integrated SW Update mechanism (swupd), I would invite you to read more on this here: https://ostroproject.org/documentation/architecture/software-update.html

For the purpose of your experiments, you should be able to add the necessary tool (e.g. opkg) to your image by adding this line to your conf/local.conf file when you build an image.
```
OSTRO_IMAGE_EXTRA_FEATURES = "package-management"
```
I'm afraid it's not possible to add `opkg` to an existing image.

I hope this helps.
